TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at processImmediate (node:internal/timers:449:9)
    at AzureOpenAiLLM.retrieveToken (file:///home/adib/evaluator/src/util/llm/wrappers/azure.ts:47:26)
    at AzureOpenAiLLM.refreshToken (file:///home/adib/evaluator/src/util/llm/wrappers/azure.ts:63:34)
    at AzureOpenAiLLM.chat (file:///home/adib/evaluator/src/util/llm/wrappers/azure.ts:85:46)
    at Chat.handleLLMChat (file:///home/adib/evaluator/src/util/llm/index.ts:228:30)
    at Chat.askChallenge (file:///home/adib/evaluator/src/util/llm/index.ts:94:25)
    at runEval (file:///home/adib/evaluator/src/eval-unit.ts:78:19) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:7760:28)
      at node:internal/deps/undici/undici:7716:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:7748:13)
      at processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}